# ORM model methods Odoo no longer has in 18.0, each mapped to the version
# that dropped it. Read from odoo and addons at odoo/18.0 (ec79381d98fd49fe8aeb4f417e3458f8d3210bb9),
# alongside the model method sets of every earlier version listed here.
#
# Generated by scripts/generate_odoo_model_stubs.py -- do not edit by hand.
# A method that only moved elsewhere in the ORM is not listed: it is still
# callable, just on something other than a recordset.

REMOVED = {
    "_add_fake_fields": "18.0",
    "_compute_concurrency_field": "17.0",
    "_field_properties_to_sql": "18.0",
    "_generate_m2o_order_by": "17.0",
    "_generate_order_by": "18.0",
    "_generate_order_by_inner": "17.0",
    "_inherits_join_add": "17.0",
    "_inherits_join_calc": "18.0",
    "_onchange_eval": "17.0",
    "_patch_method": "17.0",
    "_populate": "18.0",
    "_populate_factories": "18.0",
    "_read": "17.0",
    "_read_group_check_field_access_rights": "18.0",
    "_read_group_get_annoted_groupby": "18.0",
    "_read_group_prepare": "17.0",
    "_read_group_prepare_data": "17.0",
    "_read_group_process_groupby": "17.0",
    "_read_group_raw": "17.0",
    "_read_group_resolve_many2x_fields": "17.0",
    "_revert_method": "17.0",
    "copy_multi": "18.0",
    "fields_get_keys": "17.0",
    "get_xml_id": "17.0",
    "invalidate_cache": "17.0",
    "name_get": "18.0",
    "user_has_groups": "18.0",
}
