# ORM model methods Odoo no longer has in 17.0, each mapped to the version
# that dropped it. Read from odoo and addons at odoo/17.0 (ac703554d5c0a149ff6cc70b4632a1b29a8247ac),
# alongside the model method sets of every earlier version listed here.
#
# Generated by scripts/generate_odoo_model_stubs.py -- do not edit by hand.
# A method that only moved elsewhere in the ORM is not listed: it is still
# callable, just on something other than a recordset.

REMOVED = {
    "_compute_concurrency_field": "17.0",
    "_generate_m2o_order_by": "17.0",
    "_generate_order_by_inner": "17.0",
    "_inherits_join_add": "17.0",
    "_onchange_eval": "17.0",
    "_patch_method": "17.0",
    "_read": "17.0",
    "_read_group_prepare": "17.0",
    "_read_group_prepare_data": "17.0",
    "_read_group_process_groupby": "17.0",
    "_read_group_raw": "17.0",
    "_read_group_resolve_many2x_fields": "17.0",
    "_revert_method": "17.0",
    "fields_get_keys": "17.0",
    "get_xml_id": "17.0",
    "invalidate_cache": "17.0",
    "refresh": "17.0",
}
