# ORM model methods Odoo no longer has in 16.0, each mapped to the version
# that dropped it. Read from odoo and addons at odoo/16.0 (6a571a38b2a99175fa08dcb82f9405256a992a6c),
# alongside the model method sets of every earlier version listed here.
#
# Generated by scripts/generate_odoo_model_stubs.py -- do not edit by hand.
# A method that only moved elsewhere in the ORM is not listed: it is still
# callable, just on something other than a recordset.

REMOVED = {
}
