pub(crate) use attribute_deprecated::*;
pub(crate) use attribute_string_redundant::*;
pub(crate) use bad_builtin_groupby::*;
pub(crate) use category_allowed::*;
pub(crate) use consider_merging_classes_inherited::*;
pub(crate) use context_overridden::*;
pub(crate) use deprecated_inselect_operator::*;
pub(crate) use deprecated_method_names::*;
pub(crate) use deprecated_odoo_method_call::*;
pub(crate) use development_status_allowed::*;
pub(crate) use except_pass::*;
pub(crate) use external_request_timeout::*;
pub(crate) use field_attributes::*;
pub(crate) use header_comments::*;
pub(crate) use invalid_commit::*;
pub(crate) use invalid_email::*;
pub(crate) use license_allowed::*;
pub(crate) use manifest_author_string::*;
pub(crate) use manifest_behind_migrations::*;
pub(crate) use manifest_data_duplicated::*;
pub(crate) use manifest_deprecated_key::*;
pub(crate) use manifest_external_assets::*;
pub(crate) use manifest_maintainers_list::*;
pub(crate) use manifest_required_author::*;
pub(crate) use manifest_required_key::*;
pub(crate) use manifest_summary_multiline::*;
pub(crate) use manifest_superfluous_key::*;
pub(crate) use manifest_version_format::*;
pub(crate) use method_required_super::*;
pub(crate) use missing_odoo_file::*;
pub(crate) use missing_readme::*;
pub(crate) use missing_return::*;
pub(crate) use no_raise_unlink::*;
pub(crate) use no_search_all::*;
pub(crate) use no_wizard_in_models::*;
pub(crate) use no_write_in_compute::*;
pub(crate) use odoo_addons_relative_import::*;
pub(crate) use odoo_exception_warning::*;
pub(crate) use prefer_env_attribute::*;
pub(crate) use prefer_env_translation::*;
pub(crate) use prohibited_method_override::*;
pub(crate) use pylint_disable_comment::*;
pub(crate) use resource_not_exist::*;
pub(crate) use sql_injection::*;
pub(crate) use super_method_mismatch::*;
pub(crate) use test_folder_imported::*;
pub(crate) use translation_calls::*;
pub(crate) use translation_format::*;
pub(crate) use translation_required::*;
pub(crate) use unused_logger::*;
pub(crate) use use_vim_comment::*;
pub(crate) use website_manifest_key_not_valid_uri::*;

mod attribute_deprecated;
mod attribute_string_redundant;
mod bad_builtin_groupby;
mod category_allowed;
mod consider_merging_classes_inherited;
mod context_overridden;
mod deprecated_inselect_operator;
mod deprecated_method_names;
mod deprecated_odoo_method_call;
mod development_status_allowed;
mod except_pass;
mod external_request_timeout;
mod field_attributes;
mod header_comments;
mod invalid_commit;
mod invalid_email;
mod license_allowed;
mod manifest_author_string;
mod manifest_behind_migrations;
mod manifest_data_duplicated;
mod manifest_deprecated_key;
mod manifest_external_assets;
mod manifest_maintainers_list;
mod manifest_required_author;
mod manifest_required_key;
mod manifest_summary_multiline;
mod manifest_superfluous_key;
mod manifest_version_format;
mod method_required_super;
mod missing_odoo_file;
mod missing_readme;
mod missing_return;
mod no_raise_unlink;
mod no_search_all;
mod no_wizard_in_models;
mod no_write_in_compute;
mod odoo_addons_relative_import;
mod odoo_exception_warning;
mod prefer_env_attribute;
mod prefer_env_translation;
mod prohibited_method_override;
mod pylint_disable_comment;
mod resource_not_exist;
mod sql_injection;
mod super_method_mismatch;
mod test_folder_imported;
mod translation_calls;
mod translation_format;
mod translation_required;
mod unused_logger;
mod use_vim_comment;
mod website_manifest_key_not_valid_uri;
